Add function to verify format date
ioet/birthday_slack_bot pull request #9
Opened 2022-06-04 15:49 UTC by jcalarcon98

2022-06-04 16:04 UTC, jeffqev approved these changes

2022-06-04 16:13 UTC, Wason1797 commented on src/utils/date_utils.py
> +
Maybe combine both validations in the same if like `if not date or not is_valid_format_date() return False`

And maybe rename the function to -> `is_valid_date_format()`

2022-06-04 16:13 UTC, Wason1797 commented on src/utils/date_utils.py
> +def is_valid_format_date(date: str, date_format: str) -> bool:
maybe rename this to `is_valid_date_format()`

2022-06-04 16:14 UTC, Wason1797 commented on src/utils/date_utils.py
> +        datetime.strptime(date, date_format)
Maybe try to validate this in a different way `strptime` is kind of expensive and if we are not doing useful things with it is better to not overuse the function

2022-06-04 16:14 UTC, Wason1797 requested changes
Some minor things to address

2022-06-05 02:52 UTC, Wason1797 approved these changes
Looks good !

2022-06-06 01:34 UTC, merged